// src/store/actions/types.js
// Driver actions
export const FETCH_DRIVERS = 'FETCH_DRIVERS';
export const SELECT_DRIVER = 'SELECT_DRIVER';
export const REMOVE_DRIVER = 'REMOVE_DRIVER';

// Team actions
export const SET_TEAM_NAME = 'SET_TEAM_NAME';
export const SAVE_TEAM = 'SAVE_TEAM';
export const RESET_TEAM = 'RESET_TEAM';

// Race actions
export const FETCH_RACES = 'FETCH_RACES';
export const FETCH_RACES_SUCCESS = 'FETCH_RACES_SUCCESS';
export const FETCH_RACES_FAILURE = 'FETCH_RACES_FAILURE';

export const SET_SELECTED_RACE = 'SET_SELECTED_RACE';

export const FETCH_RACE_RESULTS = 'FETCH_RACE_RESULTS';
export const FETCH_RACE_RESULTS_SUCCESS = 'FETCH_RACE_RESULTS_SUCCESS';
export const FETCH_RACE_RESULTS_FAILURE = 'FETCH_RACE_RESULTS_FAILURE';

export const FETCH_DRIVER_STANDINGS = 'FETCH_DRIVER_STANDINGS';
export const FETCH_CONSTRUCTOR_STANDINGS = 'FETCH_CONSTRUCTOR_STANDINGS';
export const SET_CURRENT_SEASON = 'SET_CURRENT_SEASON';